### PR TITLE
Round reward mean and std in benchmark markdown file

### PR DESCRIPTION
**Pull request by qgallouedec**
## Description

In `benchmark.py`, there is no rounding procedure for the mean and std reward. Therefore, when you run `python -m utilis.benchmark`, the benchmark changes from :

```md
|algo |          env_id           |mean_reward|std_reward|n_timesteps|eval_timesteps|eval_episodes|
|-----|---------------------------|----------:|---------:|-----------|-------------:|------------:|
|a2c  |Acrobot-v1                 |    -83.353|    17.213|500k       |        149979|         1778|
|a2c  |AntBulletEnv-v0            |   2497.147|    37.359|2M         |        150000|          150|
...
```

to

```md
|algo |          env_id           |     mean_reward      |       std_reward       |n_timesteps|eval_timesteps|eval_episodes|
|-----|---------------------------|---------------------:|-----------------------:|-----------|-------------:|------------:|
|a2c  |Acrobot-v1                 |  -83.3526434195725600|   17.212852154394643000|500k       |        149979|         1778|
|a2c  |AntBulletEnv-v0            | 2497.1473654066670000|   37.358946015745644000|2M         |        150000|          150|
...
```

This PR give a fix.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [ ] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [ ] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have reformatted the code using `make format` (**required**)
- [ ] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [ ] I have ensured `make pytest` and `make type` both pass. (**required**)

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by araffin** [comment]
Hello,
thanks for the fix, do you know why the current benchmark file does not have that issue? (the current benchmark was generated automatically)

what config are you using?

**Comment by qgallouedec** [comment]
I have no idea. I never use pandas, so I guess I use the default config.

**Comment by araffin** [comment]
> I have no idea. I never use pandas, so I guess I use the default config.

maybe can you give os, python version and panda version?

**Comment by qgallouedec** [comment]
- OS: macOS-12.3.1-x86_64-i386-64bit Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
- Python: 3.8.13
- Stable-Baselines3: 1.5.0
- PyTorch: 1.11.0
- GPU Enabled: False
- Numpy: 1.22.3
- Gym: 0.21.0
- Pandas: 1.4.2

**Comment by qgallouedec** [comment]
> (normally there was a checkbox to keep when doing the PR)

"Allow edits by maintainers" has been checked. I don't understand why you can't...

**Pull request closed without merging**
