### PR TITLE
Add a callback to log raw stats

### PR DESCRIPTION
**Pull request by vwxyzjn**
This PR adds a callback to log raw (unaveraged) stats such as `episodic_length`, `episodic_returns`. The testing command is `python train.py --algo ppo --env CartPole-v1 -params callback:'"utils.callbacks.RawStatisticsCallback"' --track` and it produces this [run](https://wandb.ai/costa-huang/sb3/runs/oie42hbp)

image

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by vwxyzjn** [comment]
@araffin also suggested I do the same for `EvalCallback`. So I see that ExperimentManager already uses the `EvalCallback`, so am I replacing the `EvalCallback` with something like `RawStatsEvalCallback`?

**Comment by araffin** [comment]
> @araffin also suggested I do the same for EvalCallback. 

ah no, there was some misunderstanding on that.

**Comment by araffin** [comment]
@vwxyzjn I had to do a PR to your fork as I couldn't push to it :/

**Comment by vwxyzjn** [comment]
Added a test case and updated the changelog :)

**Review by araffin — APPROVED** [review]
LGTM =)

**Comment by vwxyzjn** [comment]
Awesome. Fell free to merg

**Comment by vwxyzjn** [comment]
Awesome. Feel free to merge

**Comment by amanuelanteneh** [comment]
Hello, I'm using this callback and am a little confused as to why the x axis isn't the episode number? It seems like what this callback does is plot the total return of an episode per timestep? Is there a way to plot the total episode reward per episode and not timestep?

**Pull request merged**
