### PR TITLE
panda-gym v2

### PR DESCRIPTION
**Pull request by qgallouedec**
## Description

Update benchmark for latest version of panda-gym.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [ ] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [x] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by araffin** [comment]
Quickly looking at it, no additional tuning was in fact required?

**Comment by araffin** [comment]
Basic version is ready to review ;)
https://github.com/DLR-RM/rl-baselines3-zoo/pull/250

An example: https://huggingface.co/sb3/ppo-MountainCarContinuous-v0

**Comment by araffin** [comment]
btw, this requires gym > 0.21, right?

**Comment by qgallouedec** [comment]
> btw, this requires gym > 0.21, right?

Yes, so it can't be merged before #256 I think

**Comment by fikricanozgur** [comment]
What's the status with this PR?

**Comment by qgallouedec** [comment]
panda-gym v2 requires gym==0.24. But, for the moment, SB3 requires gym==0.21. So the status is "waiting for SB3 to be compatible with gym>=0.24"

**Pull request closed without merging**
