### PR TITLE
Added ppo hyperparams for 10 mujoco envs

### PR DESCRIPTION
**Pull request by SonSang**
## Description
Using Optuna, I experimented with 150-200 different hyperparameters for 10 MuJoCo environments, and found the best one among them. Among the entire hyperparameters, I selected 10 best params and retrained them for 5-10 times to eliminate the biases. You can check out the optimization history graph and importances of each parameter for the environments [here](https://github.com/SonSang/rl-baselines3-zoo/tree/mujoco-ppo/mujoco_hyperparameters). 

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [ ] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [ ] I have ensured `make pytest` and `make type` both pass. (**required**)

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by araffin** [comment]
Hello,
thanks you very much for this PR.
I will try to have a closer look soon.

After a quick look, is there a reason you did not try gSDE (`use_sde=True` and `sde_sample_freq` currently commented in the hyperparameter optimization code)?

**Comment by SonSang** [comment]
Hi, thank you for the review. 

Actually there was not a specific reason for not trying gSDE. I just wanted to experiment with current default settings as specified in the code, and just left commented lines commented out.

I'm not so sure, but do you think the gSDE parameters would largely affect the optimization result? In that case I have to include them for sure.

**Comment by araffin** [comment]
>I'm not so sure, but do you think the gSDE parameters would largely affect the optimization result? In that case I have to include them for sure.

I don't think they would affect much the result (as gSDE is meanly meant for real robot training) but as I experienced with pybullet, it could lead to slightly better performance at the end (see Figure 3b in https://arxiv.org/abs/2005.05719).

**Comment by jkterry1** [comment]
@araffin so the reason we didn't include gSDE is that we ran this search for a paper we're submitting to ICLR that requires using very standard configs, and gSDE is not the standard thing everyone does for PPO. While we obviously could rerun these with gSDE, it would be very compute intensive and it's not really something we have the bandwidth for right now.

**Comment by araffin** [comment]
> While we obviously could rerun these with gSDE, it would be very compute intensive and it's not really something we have the bandwidth for right now.

No worry, was mostly asking out of curiosity.

**Pull request merged**
