### PR TITLE
Fix issue #275: training=False needed for eval envs

### LINKED ISSUE #275: VecNormalize: training should be set to False for eval environments (?)
**Describe the bug**
I don't know if this was intentional, but I do not expect normalization stats to be updated in an evaluation environment (either in an EvalCallback or in a post-train evaluation env). This can be achieved by setting `training = False` as shown below, inside the `_maybe_normalize()` function in `exp_manager.py`. If it was intentional to allow normalization stats to be updated in an eval env, then at least there should be an option to dis-allow it. 

**Code example**
This is not a code to reproduce the bug, but rather a suggestion of what to fix:
At [this line](https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/utils/exp_manager.py#L505) we should have something like this:
```
            if eval_env:
                if len(local_normalize_kwargs) > 0:
                    local_normalize_kwargs["norm_reward"] = False
                    local_normalize_kwargs["training"] = False
                else:
                    local_normalize_kwargs = {"norm_reward": False,
                                              "training": False}
```

**Additional context**
I was migrating my train + eval code to use the `ExperimentManager` and I noticed this while trying to match my results across the migration.

### PR DESCRIPTION
**Pull request by pchalasani**
Normalization stats should not be updated during evaluation, e.g. in callbacks such as `EvalCallback`. If they are updated during evaluation, it can lead to unexpected inconsistencies between results produced in eval callbacks vs post-train evaluation (where typically, normalization stats are never updated, e.g. in `enjoy.py`).

## Description

In `ExperimentManager`, made two small changes in the `_maybe_normalize()` method, 
to  `training=False` in eval environments.

## Motivation and Context

Allowing normalization stats to be updated during evaluation can lead to unexpected and puzzling inconsistencies between results produced at EvalCallback checkpoints, vs those produced by post-train evaluation runs.

Fixed #275 

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [ ] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have reformatted the code using `make format` (**required**)
- [ ] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [ ] I have ensured `make pytest` and `make type` both pass. (**required**)

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by qgallouedec** [comment]
Not really related with the core of the PR:

Why this syntax
```python
if len(local_normalize_kwargs) > 0:
    local_normalize_kwargs["norm_reward"] = False
else:
    local_normalize_kwargs = {"norm_reward": False}
```

instead of just

```python
local_normalize_kwargs["norm_reward"] = False
```
?

**Comment by pchalasani** [comment]
> Not really related with the core of the PR:
> 
> Why this syntax
> 
> ```python
> if len(local_normalize_kwargs) > 0:
>     local_normalize_kwargs["norm_reward"] = False
> else:
>     local_normalize_kwargs = {"norm_reward": False}
> ```
> 
> instead of just
> 
> ```python
> local_normalize_kwargs["norm_reward"] = False
> ```
> 
> ?

I am guessing it’s to allow for the case where 
 the dict may not exist yet.

**Comment by pchalasani** [comment]
> Not really related with the core of the PR:
> 
> Why this syntax
> 
> ```python
> if len(local_normalize_kwargs) > 0:
>     local_normalize_kwargs["norm_reward"] = False
> else:
>     local_normalize_kwargs = {"norm_reward": False}
> ```
> 
> instead of just
> 
> ```python
> local_normalize_kwargs["norm_reward"] = False
> ```
> 
> ?

That is a good point! At that point in the code, it seems like `self.normalize_kwargs` is at least an empty dict, so direct assignment would have sufficed, without needing to check for the empty case.

**Comment by pchalasani** [comment]
I just updated based on @qgallouedec 
Incidentally I am having issues installing `pybullet` so I can't run `make pytest` locally. I assume the CI actions will run tests automatically anyway.

**Comment by araffin** [comment]
thanks for the PR, overall LGTM =)
i will do some quick tests (check that it doesn't affect results) when I'm back from holidays next week ;) (you can also do some in the meantime if you have the time)

**Comment by pchalasani** [comment]
> thanks for the PR, overall LGTM =) i will do some quick tests (check that it doesn't affect results) when I'm back from holidays next week ;) (you can also do some in the meantime if you have the time)

It would affect results, in the sense that results from EvalCallback should be expected to be (slightly) different after this fix. In fact it may be good to have a unit test that checks that results from an EvalCallback with deterministic model M, deterministic env E, are identical to results from post-training evaluation with the same M loaded from a checkpoint and evaluated on E. That would be out of scope for this PR I think :)

**Comment by araffin** [comment]
*affect results too much (that the change in performance is unnoticable)

**Comment by araffin** [comment]
I did a quick check and change was as expected unnoticeable.
See below, A2C on HalfCheetahBulletEnv-v0, same seed (so training stats are the same), I plotted the evaluation curve for master and this PR, the std between the two runs is very small:
Results_HalfCheetahBullet

**Review by araffin — APPROVED** [review]
LGTM, thanks =)

Please update the changelog and we are good to go ;)

**Comment by pchalasani** [comment]
Great, I took a crack at updating the changelog, not sure what the right convention is (and unsure about release numbering and such)

**Comment by araffin** [comment]
@pchalasani did you check "allow edit from maintainers"?
I cannot push to your branch....

**Comment by pchalasani** [comment]
> @pchalasani did you check "allow edit from maintainers"? I cannot push to your branch....

yes it is checked
image

**Comment by araffin** [comment]
weird, then could you give me access to your fork (at least temporary) so I can push the edits?

**Comment by pchalasani** [comment]
sure, just added you

**Review by araffin — APPROVED** [review]

**Pull request merged**
