### PR TITLE
Fix optuna logging in saved policies

### LINKED ISSUE #196: [Bug] Problematic RL Baselines Zoo optimization information is contained in saved policies, breaking loading
### 🐛 Bug

In this PR https://github.com/DLR-RM/rl-baselines3-zoo/pull/128 several months ago, functionality was added to log optimal policies during hyperparameter optimization. I've been using this feature to debug odd behaviors in various custom environment over the past several months (using distributed optimization), and recently I started pulling saved policies off the servers for further local analysis of physics bugs.

When I started to try and load these policies locally, I got errors that I needed to install Optuna, then mysqlclient, then that it couldn't connect to the IP address of the the server with the DB optuna used for distributed optimization. Suspecting that something was included when the pickled policies were saved that shouldn't have been, I uncompressed a `best_model.zip` file, and at the bottom of the `data` file, this was contained:

```
"study": "<optuna.study.study.Study object at 0x7fbab55d3d90>",
"_trial_id": 101,
"_study_id": 1,
"storage": "<optuna.storages._cached_storage._CachedStorage object at 0x7fbab519abd0>",
"relative_search_space": {},
"relative_params": {},
"n_actions": null,
"using_her_replay_buffer": false
```

So Optuna information that shouldn't be saved really is being saved. I'm happy to submit a PR to fix this, but after spending the past 30 minutes looking through code I'm not entirely clear how this could be done, so advice would be appreciated. 

### System Info

Describe the characteristic of your environment:
 * Describe how the library was installed (pip, docker, source, ...) pip
 * GPU models and configuration T4s
 * Python version 3.7.9
 * PyTorch version torch==1.7.1+cu110
 * Gym version N/A
 * SB3 version: stable-baselines3==1.1.0a11

I know I'm using a slightly older version of pytorch/SB3, but upgrading would take a lot of work on the cluster and there's been no relevant changes to this after checking.

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ ] I have provided a minimal working example to reproduce the bug (**required**) (N/A because this requires distributed Optuna optimization and two different systems)

### PR DESCRIPTION
**Pull request by jkterry1**
## Description

This tests my understanding of the proposed fix in https://github.com/DLR-RM/rl-baselines3-zoo/issues/196. After reading the issue I assume its should just work? Also, I created the issue on the SB3 repo earlier because I had assumed it was an upstream issue in SB3 when I couldn't find the origin of the issue. 

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

closes #196 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by araffin** [comment]
> This tests my understanding of the proposed fix in #196.

Did you actually try the fix?

>  couldn't find the origin of the issue.

The origin of the issue is that SB3 try to save everything that is in the `__dict__` object of the model.

**Comment by jkterry1** [comment]
@araffin I merged this into my local branch, I'll see what happens with this and the next optimization run and update later this week.

**Comment by araffin** [comment]
> @araffin I merged this into my local branch, I'll see what happens with this in the next optimization run and update later this week.

any news about that one, did it work?

I will merge it anyway as it seems that `model.trial = trial` was for debug only.

**Comment by jkterry1** [comment]
We never ended up testing this due to a long and messy story involving CS department IT staff and changing the cluster we were using such that we never ended up needing to test it. We actually can't easily test it right now, otherwise I would

**Comment by araffin** [comment]
I tested it locally and the storage and study objects are no longer saved in `data` =)

**Review by araffin — APPROVED** [review]

**Pull request merged**
