### PR TITLE
Use discrete uniform distributions instead of categorical distributions for defining certain hyperparameter spaces

### PR DESCRIPTION
**Pull request by ycheng517**
## Description
For hyperparameter spaces that progressively increase log scale or converge towards 0 or 1, replace `suggest_categorical` with `suggest_int` and using that value as an exponent. The resulting discrete distributions are similar in value to the categorical distributions being replaced.

## Motivation and Context
closes https://github.com/DLR-RM/rl-baselines3-zoo/issues/211

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [ ] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)

### CODE REVIEW

**Comment by araffin** [comment]
Hello,
thanks for the PR, I will try to have a look this week if I have time.
In the meantime, please add user attribute with the correct values (makes it easier when reading the report, rather than having to convert values again)

Could you run a quick benchmark on simple env to see if there is actually an improvement in doing so?

**Comment by ycheng517** [comment]
Added user attribute in https://github.com/DLR-RM/rl-baselines3-zoo/pull/220/commits/2f89c11953bf2338f6b2e420f67a3609f54575e0

I performed one optimization run on MountainCar-v1 for categorical distribution and discrete log distribution respectively, and the results was actually better for the categorical distribution, but I think 1 run may not be enough sample size. 

**discrete log:**
mountain_car_50_trials_discrete_log


**categorical:**
mountain_car_50_trials_categorical

---

However, with a hypothetical problem where `y = -x`, over a large number of runs, we get better results with discrete log distribution than categorical distribution

**discrete log:**
```
def objective(trial):
    return -trial.suggest_int("x", 1, 100)

best_values_int = []
for _ in range(500):
    sampler = TPESampler(n_startup_trials=5, multivariate=True)
    study = optuna.create_study(sampler=sampler)
    study.optimize(objective, n_trials=25)
    best_values_int.append(study.best_value)
print(np.mean(best_values_int))
```
output: -100.0

**categorical:**
```
categories = list(range(1, 101))
def objective_categorical(trial):
    return -trial.suggest_categorical("param", categories)

best_values_categorical = []
for _ in range(500):
    sampler = TPESampler(n_startup_trials=5, multivariate=True)
    study = optuna.create_study(sampler=sampler, pruner=pruner)
    study.optimize(objective_categorical, n_trials=25)
    best_values_categorical.append(study.best_value)

print(np.mean(best_values_categorical))
```
output: 95.31

**Comment by jkterry1** [comment]
@araffin just following up on this since it's been a few weeks

**Comment by araffin** [comment]
> Since I use SubProcEnv for parallel rollouts, it is not efficient to send the policy to env (reward function) frequently due to communication overhead.

on my stack...

**Comment by jkterry1** [comment]
@araffin just following up on this :)

**Pull request closed without merging**
