### PR TITLE
Refactored benchmark.py

### PR DESCRIPTION
**Pull request by salmannotkhan**
now using f-string everywhere

### CODE REVIEW

**Comment by araffin** [comment]
Do you want to do the rest of the refactoring in that PR or should I merge that one first?

**Comment by salmannotkhan** [comment]
> Do you want to do the rest of the refactoring in that PR or should I merge that one first?

However you like but than we'll stick to that way to keep commits cleaner.

**Comment by araffin** [comment]
Let's do it file by file then, tell me when you are ready ;)

**Comment by salmannotkhan** [comment]
there is only one thing left why we're importing tkinter in bechmark.py

**Comment by araffin** [comment]
>there is only one thing left why we're importing tkinter in bechmark.py

It is a hack for the CI to check which backend of matplotlib to use, but matplotlib is not imported anymore I think, so you can remove that one.

**Comment by salmannotkhan** [comment]
> It is a hack for the CI to check which backend of matplotlib to use, but matplotlib is not imported anymore I think, so you can remove that one.

the whole try catch block?

**Comment by araffin** [comment]
```python
# Fix when running tests
try:
    import tkinter as Tk
except ImportError:
    matplotlib.use('agg')
```

yes, as matplotlib default backend uses tkinter...

**Comment by araffin** [comment]
I'm currently setting up github ci there #8 , I will merge with master soon, you will need to pull

**Comment by salmannotkhan** [comment]
> ```python
> # Fix when running tests
> try:
>     import tkinter as Tk
> except ImportError:
>     matplotlib.use('agg')
> ```
> 
> yes, as matplotlib default backend uses tkinter...

Then we're done you can merge.

**Comment by salmannotkhan** [comment]
> I'm currently setting up github ci there #8 , I will merge with master soon, you will need to pull

Okay

**Comment by araffin** [comment]
>Okay, First merge this and then commit your github ci. So I can have clean tree by my side.

I will squash that PR commits anyway... Did you run the tests on your side?

**Comment by salmannotkhan** [comment]
> I will squash that PR commits anyway... Did you run the tests on your side?

No, How can i run tests?

**Comment by araffin** [comment]
>No, How can i run tests?

Make sure you clone the repo with the submodule.
and then install the requirements and do `make type` and `make pytest`.

**Comment by araffin** [comment]
but if you wait 10 minutes, it will be automatic.

**Comment by salmannotkhan** [comment]
Installing requirements.txt...Big requirements for my internet ;)

**Comment by salmannotkhan** [comment]
> Make sure you clone the repo with the submodule.

What do you mean by 'with submodule'?

**Comment by araffin** [comment]
>What do you mean by 'with submodule'?

It is explained in the README (https://github.com/DLR-RM/rl-baselines3-zoo#enjoy-a-trained-agent) or the documentation of SB3. You need the `rl-trained-agents` repo.

**Comment by araffin** [comment]
>Installing requirements.txt...Big requirements for my internet ;)

You can use the cpu pytorch version (cf my branch for github ci)

**Comment by salmannotkhan** [comment]
> You can use the cpu pytorch version (cf my branch for github ci)

Half torch is downloaded anyways, so I'll wait lil bit more

**Comment by araffin** [comment]
>Half torch is downloaded anyways, so I'll wait lil bit more

The github CI is ready, it will be useful for now in the future ;)

**Comment by salmannotkhan** [comment]
So how can i use GitHub ci

**Comment by araffin** [comment]
>So how can i use GitHub ci

Just do nothing ;)

**Comment by salmannotkhan** [comment]
Did you ran the tests?

**Comment by araffin** [comment]
yes, github did

**Comment by salmannotkhan** [comment]
So does that means I don't have to test it locally on my machine:X

**Comment by araffin** [comment]
>So does that means I don't have to test it locally on my machine:X

It is always good to test locally before pushing. But know, tests are also run automatically when you open a PR.

**Pull request merged**
