### PR TITLE
Reformat files

### PR DESCRIPTION
**Pull request by salmannotkhan**
## Description

A draft PR for code refactoring

related to #5 

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [ ] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have checked the codestyle using `make lint`
- [ ] I have ensured `make pytest` and `make type` both pass.

### CODE REVIEW

**Comment by salmannotkhan** [comment]
Now Look at 
https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/utils/hyperparams_opt.py#L157
the variable `ortho_init` is unused variable which is assigned 2 times

https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/utils/hyperparams_opt.py#L320
the variable `sde_max_grad_norm` is also unsed variable

**Comment by salmannotkhan** [comment]
in train.py on [Line no. 37](https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/train.py#L37) the if statement is too complex we can simplify it by putting all that code in a function and calling that in if statement

**Comment by araffin** [comment]
> the variable ortho_init is unused variable which is assigned 2 times

I see... it should be added to `'policy_kwargs': dict(log_std_init=log_std_init, net_arch=net_arch, activation_fn=activation_fn)`

> the variable sde_max_grad_norm is also unsed variable

you can delete that one. It was used in the `sde` branch but not in master anymore.

**Comment by araffin** [comment]
>in train.py on Line no. 37 the if statement is too complex we can simplify it by putting all that code in a function and calling that in if statement

you can ignore that one, it does not change much

**Comment by salmannotkhan** [comment]
In test_optimize function of test_hyperparams_opt there are unmatched brackets [HERE](https://github.com/DLR-RM/rl-baselines3-zoo/blob/ed0028586ba066e702d82065aee52fa2ae90eca6/tests/test_hyperparams_opt.py#L48)

**Comment by salmannotkhan** [comment]
and what about this import [here](https://github.com/DLR-RM/rl-baselines3-zoo/blob/ed0028586ba066e702d82065aee52fa2ae90eca6/train.py#L12)

**Comment by araffin** [comment]
>In test_optimize function of test_hyperparams_opt there are unmatched brackets HERE

I see... this is a pure hack to make the test run faster without duplicating the code for ppo.

>and what about this import here

this is a remain, you can remove... I handle that in the yaml file now.

**Comment by salmannotkhan** [comment]
So i guess this is it. Please Confirm all edits I made.

**Comment by salmannotkhan** [comment]
So, I'll make chnages in changelog tomorrow.

**Comment by araffin** [comment]
@salmannotkhan are you done? (if so, please make it "ready to review")

**Pull request merged**
