### PR TITLE
Update Hugging Face 🤗 Push To Hub

### PR DESCRIPTION
**Pull request by simoninithomas**
## Description

Due to Gymnasium updates, we need to update RL-Baselines3-Zoo push_to_hub.py file.

To fit Gymnasium needs, I added an env_kwargs update (since we need to indicate the render_mode with gymnasium). Though it has a bug if you print env.render_mode, it will still be None.

The complete issue:
```Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/rl_zoo3/push_to_hub.py", line 407, in <module>
    package_to_hub(
  File "/usr/local/lib/python3.10/dist-packages/rl_zoo3/push_to_hub.py", line 247, in package_to_hub
    _generate_replay(model, eval_env, video_length, is_deterministic, repo_local_path)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_sb3/push_to_hub.py", line 128, in _generate_replay
    env = VecVideoRecorder(
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/vec_video_recorder.py", line 50, in __init__
    assert self.env.render_mode == "rgb_array", f"The render_mode must be 'rgb_array', not {self.env.render_mode}"
AssertionError: The render_mode must be 'rgb_array', not None
Exception ignored in: <function VecVideoRecorder.__del__ at 0x7f8d63043d00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/vec_video_recorder.py", line 113, in __del__
    self.close_video_recorder()
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/vec_video_recorder.py", line 103, in close_video_recorder
    if self.recording:
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 377, in __getattr__
    return self.getattr_recursive(name)
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 400, in getattr_recursive
    attr = self.venv.getattr_recursive(name)
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 402, in getattr_recursive
    attr = getattr(self.venv, name)
AttributeError: 'DummyVecEnv' object has no attribute 'recording'
```

To reproduce this issue: 

https://colab.research.google.com/drive/1RygEbqaNUGXD7t1J8FPvrB1OQLpD_JpF?usp=sharing

Thanks 🤗 

## Motivation and Context

This change is required to work with Gymnasium (video generation)

- [ ] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [X] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [ ] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have reformatted the code using `make format` (**required**)
- [ ] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [ ] I have ensured `make pytest` and `make type` both pass. (**required**)

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by araffin** [comment]
Hello,
thanks for the PR, it needs to be updated indeed (it is not included in the test because we would need to upload something to hf every time, maybe is there a dry run option?)

I see it is a WIP, what is missing?


> Though it has a bug if you print env.render_mode, it will still be None.

What do you mean? (I will check later)

btw, I'm still interested in having your DRL course in SB3 doc ;)

**Comment by araffin** [comment]
> So I've added it though it seems given the error message that this render_mode is not passed to the environment (with env_kwargs).


Alright, tell me if you need help/testing.

**Comment by araffin** [comment]
So, I just tested locally and it works fine, will see with colab.
Btw, I couldn't push my edits to your branch :/

See https://github.com/DLR-RM/rl-baselines3-zoo/commit/a9bdbcee93732b2999675032b14635dba5f815cf

**Comment by araffin** [comment]
So, I tested it myself here (with cartpole) and I could not reproduce the issue...
https://colab.research.google.com/drive/1lajCqGE-7rNxM8tAy805XSxA-mwqWB4y?usp=sharing

I will try again with an atari game, that might be the issue.

**Comment by araffin** [comment]
My current guess is that you had an old version of ale-py and were facing this issue: https://github.com/mgbellemare/Arcade-Learning-Environment/pull/476

**Comment by araffin** [comment]
I had to patch atari before (https://github.com/DLR-RM/rl-baselines3-zoo/pull/357/commits/4e019e8e7e971c78a23beff569c3d365afc3326f), let me see if it's still needed locally.

**Comment by araffin** [comment]
So, I can confirm that it works with this patch: https://github.com/DLR-RM/rl-baselines3-zoo/commit/4e019e8e7e971c78a23beff569c3d365afc3326f (I pushed it to my branch)

Something is wrong with `VecFrameStack`, `env.unwrapped.render_mode` (dummy vec env) is correct but not `env.render_mode` (vec frame stack).

**Comment by simoninithomas** [comment]
Sorry for not being able to commit in the HF fork's branch directly I added you to the fork so that next time it will be easier 🤗 

I'm testing your branch: update/hf. And I suppose I can close this PR?

**Comment by araffin** [comment]
As I wrote in https://github.com/DLR-RM/stable-baselines3/pull/1525, SB3 update will fix the Atari recording issue, HF SB3 update (https://github.com/huggingface/huggingface_sb3/pull/25).

**Review by araffin — COMMENTED** [review]
@simoninithomas Could you check that version?
I think it should work for all envs now =)

**Comment by simoninithomas** [comment]
Normally this version will not work for SB3 + Panda Gyms
But it will work for RL-Zoo.

So either:
1. You can wait for this Monday for 2.5.6 and modify the requirements to 2.5.6
2. Or we can merge it now. Given it's not related to RL-Zoo.

**Comment by VineetTambe** [comment]
Was this issue solved?  I am trying to run record video. This is the command I am trying to run:
```
python -m rl_zoo3.record_video --algo ppo --env MiniGrid-FourRooms-v0 --exp-id 0 -f logs/ -n 1000
```

If so, could you let me know how I just see version updates in this PR and no major changes to `record_video.py`? 
I am facing the exact same issue with the `MiniGrid-FourRooms-v0` environment.

Any help would be greatly appriciated!

**Comment by VineetTambe** [comment]
Have narrowed it down to `VecNormalize` in `utilis.py` env.render_mode is set to None after line [284](https://github.com/DLR-RM/rl-baselines3-zoo/blob/2d5db11f6aee6d231d2154849715b0f7a9435038/rl_zoo3/utils.py#L284). So should this issue be raised in the stable-baselines3 repo instead?

**Comment by araffin** [comment]
> Have narrowed it down to `VecNormalize` in `utilis.py` env.render_mode is set to None after line [284](https://github.com/DLR-RM/rl-baselines3-zoo/blob/2d5db11f6aee6d231d2154849715b0f7a9435038/rl_zoo3/utils.py#L284). So should this issue be raised in the stable-baselines3 repo instead?

if you look at the conversation of this PR, it is fixed in https://github.com/DLR-RM/stable-baselines3/pull/1525, you should upgrade your SB3 version (that's what this PR is also about).

**Pull request merged**
