### PR TITLE
Replace deprecated use of 'Repository' when pushing to hub with `HfApi`

### LINKED ISSUE #463: Replace Deprectated Repository with HfApi
### 🚀 Feature

I got various errors uploading my models to huggingface_hub (didn't include this as a bug report as even the proposed commit that should have fixed my issue worked in my particular context), all related to the Repository object. This class seems to be deprecated.

### Motivation

The use of the use of Repository should be replaced by using the HfApi object (https://huggingface.co/docs/huggingface_hub/concepts/git_vs_http).

### Pitch

_No response_

### Alternatives

As mentioned before, there should have been a fix in the huggingface_hub repository (this fix is not yet published to pipy: https://github.com/huggingface/huggingface_hub/pull/2320)

### Additional context

Already fixed in PR #462 😄 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo

### PR DESCRIPTION
**Pull request by cochaviz**
# Remove deprecated use of 'Repository' when pushing to huggingface hub

## Description

As mentioned above, use of the `Repository` class is deprecated: <https://hu…ggingface.co/docs/huggingface_hub/concepts/git_vs_http>.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

Closes #463 🥳 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by araffin** [comment]
Hello,
thanks for the PR, could you rebase your PR from master instead of the `update/hf` branch?

**Comment by cochaviz** [comment]
> Hello, thanks for the PR, could you rebase your PR from master instead of the `update/hf` branch?

I just want to double-check whether what I'm doing now is also okay: I will cherry-pick the commits I made to the branch and add them to master. Should I then create a new PR that originates from master?

Sorry for the hassle, I haven't contributed much to open-source so I'm not incredibly familiar with all the conventions! 🥲 (I was following the huggingface course when I found this issue, and though `hf` stood for that... Now I realize it probably stands for `hotfix` 😅 )

**Comment by araffin** [comment]
> I will cherry-pick the commits I made to the branch and add them to master. Should I then create a new PR that originates from master?

Almost. Start from master, create a new branch, cherry-pick the commits and then push (you could even force push to this branch).

**Comment by qgallouedec** [comment]
Closing in favour of #465

**Pull request closed without merging**
